// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAwUGq02SE-A38jc5iGSRH0-0g_TdgD8U',
    appId: '1:314585985777:web:d6a6b9d1d618699e32ef50',
    messagingSenderId: '314585985777',
    projectId: 'daftar-belanja-41e30',
    authDomain: 'daftar-belanja-41e30.firebaseapp.com',
    databaseURL: 'https://daftar-belanja-41e30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-41e30.firebasestorage.app',
    measurementId: 'G-4CD3BNX3DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiAKP28AOYnk3yzygE2bvwJ5Z3uChj-Ck',
    appId: '1:314585985777:android:8fa67fe83d0ebe3b32ef50',
    messagingSenderId: '314585985777',
    projectId: 'daftar-belanja-41e30',
    databaseURL: 'https://daftar-belanja-41e30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-41e30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvaDcFQs_jkk6GnjNpySGYFc-ngP6SukM',
    appId: '1:314585985777:ios:d539f3831e70519032ef50',
    messagingSenderId: '314585985777',
    projectId: 'daftar-belanja-41e30',
    databaseURL: 'https://daftar-belanja-41e30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-41e30.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvaDcFQs_jkk6GnjNpySGYFc-ngP6SukM',
    appId: '1:314585985777:ios:d539f3831e70519032ef50',
    messagingSenderId: '314585985777',
    projectId: 'daftar-belanja-41e30',
    databaseURL: 'https://daftar-belanja-41e30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-41e30.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAwUGq02SE-A38jc5iGSRH0-0g_TdgD8U',
    appId: '1:314585985777:web:8a93faf70812a13032ef50',
    messagingSenderId: '314585985777',
    projectId: 'daftar-belanja-41e30',
    authDomain: 'daftar-belanja-41e30.firebaseapp.com',
    databaseURL: 'https://daftar-belanja-41e30-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'daftar-belanja-41e30.firebasestorage.app',
    measurementId: 'G-QLL3WBRQF1',
  );
}
